version: '3.8'

services:
  php-mvc:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
  db:
    image: mysql:5.7.21
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: manusia
      MYSQL_PASSWORD: bernapas
      MYSQL_DATABASE: phpmvc
      MYSQL_ROOT_PASSWORD: bernapas
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  dbdata:
